[project.urls]
Homepage = "https://github.com/ONE-ORIGINE/axiomesh-sdk"
Source = "https://github.com/ONE-ORIGINE/axiomesh-sdk"
Issues = "https://github.com/ONE-ORIGINE/axiomesh-sdk/issues"
Documentation = "https://github.com/ONE-ORIGINE/axiomesh-sdk#readme"
Changelog = "https://github.com/ONE-ORIGINE/axiomesh-sdk/blob/main/CHANGELOG.md"